name: gh-pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          mamba-version: "*"
          python-version: "3.12"
          activate-environment: doc
          conda-remove-defaults: "true"

      - name: Dependencies
        shell: bash -l {0}
        run: |
          # Compilation related dependencies
          mamba install cmake make pkg-config doxygen graphviz

          # Main dependencies
          mamba install eigen pinocchio fmt proxsuite-nlp example-robot-data

      - name: Print environment
        shell: bash -l {0}
        run: |
          conda info
          mamba list
          env

      - name: Configure
        shell: bash -l {0}
        run: |
          git submodule update --init
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_INTERFACE:BOOL=OFF\
            -DPYTHON_EXECUTABLE=$(which python3) -DBUILD_DOCUMENTATION:BOOL=ON \
            -DBUILD_BENCHMARKS:BOOL=OFF -DINSTALL_DOCUMENTATION:BOOL=ON -DBUILD_TESTING:BOOL=OFF \
            -DBUILD_CROCODDYL_COMPAT:BOOL=OFF

      - name: Build documentation
        shell: bash -l {0}
        run: |
          cd build
          cmake --build . --config Release --target doc

      - name: Upload to GitHub pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/doc/doxygen-html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        id: deployment
